#!/bin/bash

# Runs several docker commands in order
## docker-compose down
## if (-b) docker-compose build
## docker-compose up -d
## if (-f) docker-compose logs -f

docker-compose down
BUILD=false
FOLLOW=false
while getopts "bf" opt; do
  case $opt in
    b)
      BUILD=true
      ;;
    f)
      FOLLOW=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

if [ $BUILD = true ]; then
  docker-compose build
	error=$?
	if [[ $error -ne 0 ]]; then
		exit $error
	fi
fi
docker-compose up -d
if [ $FOLLOW = true ]; then
  docker-compose logs -f
fi
