#!/bin/bash
folder=${PWD##*/}
container_name=${folder}
containers=$(get_completions "docker exec -it $container_name")

container=''
for possible in $containers; do
    if ! [[ $possible =~ 'postgres' ]]; then
        container=$possible
        break
    fi
done

docker exec -it $container "$@"
