#!/bin/bash
folder=${PWD##*/}
container_name=${folder//_}
containers=$(get_completions "docker exec -it $container_name")

container=''
for possible in $containers; do
    if [[ $possible =~ 'postgres' ]]; then
        container=$possible
        break
    fi
done

# Currently assumes that the name of the database is the same as the name of the container
docker exec -it $container bash -c -it "su postgres -c \"psql ${container_name}\""
